services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cf_ddns
    network_mode: host
    restart: always
    # Restart the updater after reboot
    user: "1000:131"
    read_only: true
    cap_drop: [all]
    security_opt: [no-new-privileges:true]
    env_file:
      - /run/agenix/cf-token
    environment:
        # Your Cloudflare API token
        #- CLOUDFLARE_API_TOKEN= got from agenix
        # Your domains (separated by commas)
      - DOMAINS=*.mariolamasangeriz.net
      - PROXIED=false
      - IP6_PROVIDER=none
