# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cf_ddns" = {
    image = "favonia/cloudflare-ddns:latest";
    environmentFiles = [
      "/run/agenix/cf-token"
    ];
    environment = {
      "DOMAINS" = "*.mariolamasangeriz.net";
      "IP6_PROVIDER" = "none";
      "PROXIED" = "false";
    };
    user = "1000:131";
    log-driver = "journald";
    extraOptions = [
      "--cap-drop=all"
      "--network=host"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."docker-cf_ddns" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    partOf = [
      "docker-compose-ddns-root.target"
    ];
    wantedBy = [
      "docker-compose-ddns-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ddns-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
