# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Containers
  virtualisation.oci-containers.containers."grafana" = {
    image = "grafana/grafana:latest";
    environment = {
      "GF_AUTH_ANONYMOUS_ENABLED" = "true";
      "GF_AUTH_ANONYMOUS_ORG_NAME" = "Main Org.";
      "GF_AUTH_ANONYMOUS_ORG_ROLE" = "Viewer";
      "GF_AUTH_DISABLE_LOGIN_FORM" = "false";
      "GF_SECURITY_ADMIN_PASSWORD" = "z_123.";
      "GF_USERS_VIEWERS_CAN_EDIT" = "false";
    };
    volumes = [
      "/srv/docker/grafana-container/data:/var/lib/grafana:rw"
      "${../../docker/monitoring/grafana-container/dashboard.json}:/etc/grafana/provisioning/dashboards/dashboard.json:ro"
      "${pkgs.writeText "provider.yaml" ''
      apiVersion: 1
      providers:
        - name: 'nixos-dashboards'
          type: file
          options: 
            path: /etc/grafana/provisioning/dashboards
      ''}:/etc/grafana/provisioning/dashboards/provider.yaml:ro"
    ];
    ports = [
      "3000:3000/tcp"
    ];
    user = "1000:131";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=grafana"
      "--network=monitoring-network"
    ];
  };
  systemd.services."docker-grafana" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-monitoring-network.service"
    ];
    requires = [
      "docker-network-monitoring-network.service"
    ];
    partOf = [
      "docker-compose-grafana-root.target"
    ];
    wantedBy = [
      "docker-compose-grafana-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-monitoring-network" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f monitoring-network";
    };
    script = ''
      docker network inspect monitoring-network || docker network create monitoring-network --driver=bridge
    '';
    partOf = [ "docker-compose-grafana-root.target" ];
    wantedBy = [ "docker-compose-grafana-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-grafana-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
