# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Containers
  virtualisation.oci-containers.containers."prometheus" = {
    image = "prom/prometheus:latest";
    volumes = [
      "/srv/docker/prometheus-container/data:/prometheus:rw"
      "${../../docker/monitoring/prometheus-container/prometheus.yml}:/etc/prometheus/prometheus.yml:ro"
    ];
    cmd = [ "--config.file=/etc/prometheus/prometheus.yml" "--storage.tsdb.path=/prometheus" ];
    user = "1000:131";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=prometheus"
      "--network=monitoring-network"
    ];
  };
  systemd.services."docker-prometheus" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-monitoring-network.service"
    ];
    requires = [
      "docker-network-monitoring-network.service"
    ];
    partOf = [
      "docker-compose-prometheus-root.target"
    ];
    wantedBy = [
      "docker-compose-prometheus-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-prometheus-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
